# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json#/definitions/page

- name: Pi Comms Landing
  head-widgets:
    - type: search
      title: Google it
      search-engine: google
      new-tab: true
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: Europe/Dublin
              name: Belfast
        - type: calendar
          first-day-of-week: monday
        - type: weather
          location: Belfast, United Kingdom
          units: metric
          hour-format: 24h
          hide-location: true
    - size: full
      widgets:
        - type: split-column
          widgets:
            - type: bookmarks
              title: Projects
              groups:
                - title: Disaster Recovery
                  links:
                    - title: Working Document
                      url: https://documents.cothrom.ie/p/NIA_Assembly_DR
                    - title: Data Tables
                      url: https://data.cothrom.ie
                - title: VCAS OnDemand Refresh
                  links:
                    - title: Working Document
                      url: https://documents.cothrom.ie/p/NIA_VCAS_OD_Refresh
            - type: bookmarks
              # title: company
              groups:
                - links:
                  - title: NIA Buisness Diary
                    url: https://aims.niassembly.gov.uk/assemblybusiness/businessdiary.aspx
                  - title: Vimeo
                    url: https://www.vimeo.com
                  - title: Fault Log
                    url: https://www.airtable.com
                  - title: NIA IP Address Log
                    url: https://docs.google.com/spreadsheets/d/15e8r2j-wWONs9QBlmVewPKXYqo2VxMaxx85b4Tp8vzk/


        - type: to-do
    - size: small
      widgets:
        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
              chart-link: https://www.tradingview.com/chart/?symbol=INDEX:BTCUSD
            - symbol: GBPUSD
              name: GBPUSD
            - symbol: AAPL
              symbol-link: https://www.google.com/search?tbm=nws&q=apple
              name: Apple
        - type: reddit
          subreddit: news
