pageInfo:
  title: Cothrom
  description: Cothrom is my freelancing deployment for Docker

appConfig:
  language: en-GB
  defaultOpeningMethod: newtab
  statusCheck: true
  webSearch:
    searchEngine: google
    openingMethod: newtab

sections:
- name: Apps
  items:
    - title: Accounts
      url: https://accounts.cothrom.ie
      description: Accounts is a platform for managing your finances.
      statusCheckUrl: https://accounts.cothrom.ie
    - title: AppSmith
      url: https://apps.cothrom.ie
      description: AppSmith is a platform for building and deploying web applications.
      statusCheckUrl: https://apps.cothrom.ie
    - title: Cal Server
      url: https://cal.cothrom.ie
      description: Cal Server is a platform for managing your calendar.
      statusCheckUrl: https://cal.cothrom.ie
    - title: CRM Server
      url: https://crm.cothrom.ie
      description: CRM Server is a platform for managing your customers and projects.
      statusCheckUrl: https://crm.cothrom.ie
    - title: Data
      url: https://data.cothrom.ie
      description: NocoDB
      statusCheckUrl: https://data.cothrom.ie
    - title: Documents
      url: https://documents.cothrom.ie
      description: Etherpad.
      statusCheckUrl: https://documents.cothrom.ie
    - title: Draw Server
      url: https://draw.cothrom.ie
      description: Excalidraw.
      statusCheckUrl: https://draw.cothrom.ie
    - title: Files
      url: https://files.cothrom.ie
      description: File Sharing.
      statusCheckUrl: https://files.cothrom.ie
    - title: Grammar
      url: https://grammar.cothrom.ie
      description: Language Tool.
      statusCheckUrl: https://grammar.cothrom.ie
