services:
  cal_baikal:
    image: ckulka/baikal:nginx
    container_name: cal_baikal
    restart: always
    ports:
      - '${CAL_PORT}:80'
    volumes:
      - cal_config:/var/www/baikal/config
      - cal_data:/var/www/baikal/Specific
      - ${BACKUP_DIR}/cal:/backup
    networks:
      - frontend
      - database
    depends_on:
      cal_db:
        condition: service_healthy
    labels:
      ## database | app | proxy | worker | cache | storage
      - io.cothrom.role="app"
      - io.cothrom.stack="cal"
      - io.cothrom.data="true"
      # database | files | config
      - io.cothrom.data.class="config"
      # postgres | mysql | mariadb | redis
      # - io.cothrom.db.engine="mysql"
      # - io.cothrom.db.backup.command=pg_dump -U $POSTGRES_USER -d $POSTGRES_DB
      # - io.cothrom.db.backup.command="mysqldump -u $MYSQL_USER -p $MYSQL_ROOT_PASSWORD $MYSQL_DATABASE"
      # daily | hourly | weekly
      - io.cothrom.backup.policy="weekly"

  cal_db:
    container_name: cal_db
    environment:
      POSTGRES_DB: cal
      POSTGRES_PASSWORD: ${CAL_POSTGRES_PASSWORD}
      POSTGRES_USER: cal
    healthcheck:
      interval: 10s
      retries: 10
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"cal\""]
      timeout: 2s
    image: postgres:17-bookworm
    restart: always
    volumes:
      - cal_db:/var/lib/postgresql/data
    networks:
      - database
    labels:
          ## database | app | proxy | worker | cache | storage
      - io.cothrom.role="database"
      - io.cothrom.stack="cal"
      - io.cothrom.data="true"
      # database | files | config
      - io.cothrom.data.class="database"
      # postgres | mysql | mariadb | redis
      - io.cothrom.db.engine="postgres"
      - io.cothrom.db.backup.command="pg_dump -U $POSTGRES_USER -d $POSTGRES_DB"
      # - io.cothrom.db.backup.command="mysqldump -u $MYSQL_USER -p $MYSQL_ROOT_PASSWORD $MYSQL_DATABASE"
      # daily | hourly | weekly
      - io.cothrom.backup.policy="weekly"

volumes:
  cal_config:
  cal_data:
  cal_db:
