volumes:
  company_dolibarr_html:
  company_dolibarr_docs:
  company_dolibarr_db:

services:

  company_mariadb:
    image: mariadb:noble
    container_name: company_mariadb
    networks:
      - database
    restart: always
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - company_dolibarr_db:/var/lib/mysql
    environment:
        - MYSQL_DATABASE=company_dolibarr
        - MYSQL_USER=dolibarr
        - MYSQL_PASSWORD=${COMPANY_DB_PASSWORD}
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
    labels:
          ## database | app | proxy | worker | cache | storage
      - io.cothrom.role="database"
      - io.cothrom.stack="company"
      - io.cothrom.data="true"
      # database | files | config
      - io.cothrom.data.class="database"
      # postgres | mysql | mariadb | redis
      - io.cothrom.db.engine="mariadb"
      # - io.cothrom.db.backup.command=pg_dump -U $POSTGRES_USER -d $POSTGRES_DB
      - io.cothrom.db.backup.command="mysqldump -u $MYSQL_USER -p $MYSQL_ROOT_PASSWORD $MYSQL_DATABASE"
      # daily | hourly | weekly
      - io.cothrom.backup.policy="daily"

  company_dolibarr:
    image: upshift/dolibarr:latest
    container_name: company_dolibarr
    networks:
      - frontend
      - database
    restart: always
    depends_on:
        - company_mariadb
    ports:
        - ${COMPANY_PORT}:80
    environment:
        - DOLI_DB_HOST=company_mariadb
        - DOLI_DB_NAME=company_dolibarr
        - DOLI_DB_USER=dolibarr
        - DOLI_DB_PASSWORD=${COMPANY_DB_PASSWORD}
        - DOLI_ADMIN_LOGIN=${COMPANY_ADMIN_LOGIN}
        - DOLI_ADMIN_PASSWORD=${COMPANY_ADMIN_PASSWORD}
        - DOLI_COMPANY_NAME=${COMPANY_NAME}
        - DOLI_COMPANY_COUNTRYCODE=${COUNTRY_CODE}
        - WWW_USER_ID=${PUID:-1000}
        - WWW_GROUP_ID=${PGID:-1000}
    volumes:
        - company_dolibarr_html:/var/www/html
        - company_dolibarr_docs:/var/www/documents
        - ${BACKUP_DIR}/company/dolibarr:/backup
    labels:
          ## database | app | proxy | worker | cache | storage
      - io.cothrom.role="app"
      - io.cothrom.stack="company"
      - io.cothrom.data="true"
      # database | files | config
      - io.cothrom.data.class="config"
      # postgres | mysql | mariadb | redis
      # - io.cothrom.db.engine="mysql"
      # - io.cothrom.db.backup.command=pg_dump -U $POSTGRES_USER -d $POSTGRES_DB
      # - io.cothrom.db.backup.command="mysqldump -u $MYSQL_USER -p $MYSQL_ROOT_PASSWORD $MYSQL_DATABASE"
      # daily | hourly | weekly
      # - io.cothrom.backup.policy="daily"
