###
### Definitions
###

x-op-app-network: &app-network
  networks:
    - database
    - frontend
x-op-app-restart-policy: &app_restart_policy
  restart: unless-stopped
x-op-db-restart-policy: &db_restart_policy
  restart: always
x-op-healthcheck-postgres-policy: &post_health_policy
  healthcheck:
    interval: 10s
    retries: 10
    test: ['CMD-SHELL', 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
    timeout: 2s
x-op-postgres-image: &post-image
  image: postgres:17-bookworm
x-op-postgres-network: &db-network
  networks:
    - database

###
### Services
###

services:
  data_nocodb:
    depends_on:
      data_nocodb_db:
        condition: service_healthy
    environment:
      NC_DB: 'pg://data_nocodb_db:5432?u=postgres&p=password&d=data_nocodb_db'
    image: 'nocodb/nocodb:latest'
    container_name: data_nocodb
    ports:
      - ${DATA_PORT}:8080
    <<: [*app_restart_policy, *app-network]
    volumes:
      - data_nocodb:/usr/app/data
      - ${BACKUP_DIR}/data/nocodb:/backup

  data_nocodb_db:
    container_name: data_nocodb_db
    environment:
      POSTGRES_DB: data_nocodb_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    <<: [*post_health_policy, *db_restart_policy, *post-image, *db-network]
    volumes:
      - data_nocodb_db:/var/lib/postgresql/data

  data_pgadmin:
    container_name: data_pgadmin
    image: dpage/pgadmin4:latest
    <<: [*app_restart_policy, *app-network]
    volumes:
      - data_pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ADMIN_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0

volumes:
  data_nocodb:
  data_nocodb_db:
  data_pgadmin:

include:
  - path: ./datastorage.yml
