################## Snippets ##################
x-op-docs-restart-policy: &docs-restart-policy
  restart: unless-stopped

################## Volumes ##################
volumes:
  docs-data:
  docs-media:
  docs-pgdata:
  docs-redis:

################## Services ##################
services:
  docs-cache:
    image: docker.io/library/redis:8
    container_name: docs-cache
    networks:
      - database
    <<: [*docs-restart-policy]
    volumes:
      - docs-redis:/data

  docs-db:
    image: docker.io/library/postgres:18-bookworm
    container_name: docs-db
    networks:
      - database
    <<: [*docs-restart-policy]
    volumes:
      - docs-pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${DOCS_DB_NAME:-paperless}
      POSTGRES_USER: ${DOCS_DB_USER:-paperless}
      POSTGRES_PASSWORD: ${DOCS_DB_PASSWORD:-paperless}

  docs-paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: docs-paperless
    networks:
      - database
      - backend
      - frontend
    <<: [*docs-restart-policy]
    depends_on:
      - docs-db
      - docs-cache
      - docs-gotenberg
      - docs-tika
    ports:
      - ${DOCS_PORT:-8000}:8000
    volumes:
      - ${DOCS_DATA_VOL:-docs-data}:/usr/src/paperless/data
      - ${DOCS_MEDIA_VOL:-docs-data}:/usr/src/paperless/media
      - ${DOCS_EXPORT_PATH:-./export}:/usr/src/paperless/export
      - ${DOCS_CONSUME_PATH:-./consume}:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://docs-cache:6379
      PAPERLESS_DBHOST: docs-db
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBNAME: ${DOCS_DB_NAME:-paperless}
      PAPERLESS_DBUSER: ${DOCS_DB_USER:-paperless}
      PAPERLESS_DBPASS: ${DOCS_DB_PASSWORD:-paperless}
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://docs-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://docs-tika:9998
      PAPERLESS_SECRET_KEY: ${DOCS_SECRET_KEY:-change-me-im-very-important-and-stuff}
      PAPERLESS_TIME_ZONE: ${TZ:-Europe/Dublin}
      USERMAP_UID: ${PUID:-1000}
      USERMAP_GID: ${PGID:-1000}
      PAPERLESS_URL: ${DOCS_URL:-https://paperless.example.com}
      PAPERLESS_OCR_LANGUAGE: ${DOCS_OCR_LANG:-eng}
      PAPERLESS_EMAIL_HOST: ${EMAIL_SMTP_HOST:-smtp.gmail.com}
      PAPERLESS_EMAIL_PORT: ${EMAIL_SMTP_PORT:-587}
      PAPERLESS_EMAIL_HOST_USER: ${EMAIL_SMTP_USER:-your_email@gmail.com}
      PAPERLESS_EMAIL_HOST_PASSWORD: ${EMAIL_SMTP_PASSWORD:-your_email_password}
      PAPERLESS_EMAIL_FROM: ${EMAIL_SYSTEM_ADDRESS:-your_email@gmail.com}
      PAPERLESS_EMAIL_USE_SSL: ${EMAIL_SMTP_USE_SSL:-false}
      PAPERLESS_EMAIL_USE_TLS: ${EMAIL_SMTP_USE_TLS:-false}

  docs-gotenberg:
    container_name: docs-gotenberg
    networks:
      - backend
    image: docker.io/gotenberg/gotenberg:8.27
    <<: [*docs-restart-policy]
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - 'gotenberg'
      - '--chromium-disable-javascript=true'
      - '--chromium-allow-list=file:///tmp/.*'

  docs-tika:
    <<: [*docs-restart-policy]
    container_name: docs-tika
    networks:
      - backend
    image: docker.io/apache/tika:latest
    restart: unless-stopped

  # docs-docling:
  #   image: ghcr.io/docling-project/docling-serve-cu126:main
  #   container_name: docs-docling
  #   ports:
  #     - ${DOCS_DOC_PORT:-5001}:5001
  #   environment:
  #     DOCLING_SERVE_ENABLE_UI: "true"
  #     NVIDIA_VISIBLE_DEVICES: "all"
  #     DOCLING_SERVE_ENABLE_REMOTE_SERVICES: "true"
  #     DOCLING_SERVE_MAX_SYNC_WAIT: 600
  #     DOCLING_SERVE_ENG_LOC_NUM_WORKERS: 2
  #     OMP_NUM_THREADS: 4
  #     MKL_NUM_THREADS: 4
  #     UVICORN_WORKERS: 1
  #   # runtime: nvidia
  #   restart: unless-stopped
  #   networks:
  #     - backend
  #     - frontend
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: all

  # paperless-gpt:
  #   image: icereed/paperless-gpt:latest # Docker Hub
  #   environment:
  #     PAPERLESS_BASE_URL: 'http://docs-paperless:8000'
  #     PAPERLESS_API_TOKEN: ${DOCS_API_TOKEN:-your_paperless_api_token}
  #     PAPERLESS_PUBLIC_URL: ${DOCS_URL}
  #     MANUAL_TAG: 'paperless-gpt'
  #     AUTO_TAG: 'paperless-gpt-auto'

  #     # Ollama
  #     # LLM_PROVIDER: 'ollama'
  #     # LLM_MODEL: ${DOCS_LLM_MODEL:-qwen3:latest}
  #     # OLLAMA_HOST: ${OLLAMA_HOST:-http://host.docker.internal:11434}
  #     # OLLAMA_CONTEXT_LENGTH: ${OLLAMA_CONTEXT_LENGTH:-8192}
  #     # TOKEN_LIMIT: ${DOCS_TOKEN_LIMIT:-1000}

  #     # OpenAI
  #     LLM_PROVIDER: 'openai'
  #     LLM_MODEL: ${DOCS_LLM_MODEL:-deepseek/deepseek-v4-flash}
  #     OPENAI_API_KEY: ${DOCS_OPENAI_API_KEY}
  #     OPENAI_API_TYPE: 'azure'
  #     OPENAI_BASE_URL: ${DOCS_OPENAI_BASE_URL:-https://openrouter.ai/api/v1}

  #     # OCR Configuration - Choose one:
  #     OCR_PROVIDER: 'llm' # Default OCR provider
  #     VISION_LLM_PROVIDER: 'openai' # openai, ollama, mistral, or anthropic
  #     VISION_LLM_MODEL: ${DOCS_VISION_LLM_MODEL:-minicpm-v}

  #     OCR_PROCESS_MODE: 'image' # Optional, default: image, other options: pdf, whole_pdf
  #     PDF_SKIP_EXISTING_OCR: 'false' # Optional, skip OCR for PDFs with existing OCR

  #     # Enhanced OCR Features
  #     CREATE_LOCAL_HOCR: 'false' # Optional, save hOCR files locally
  #     LOCAL_HOCR_PATH: '/app/hocr' # Optional, path for hOCR files
  #     CREATE_LOCAL_PDF: 'false' # Optional, save enhanced PDFs locally
  #     LOCAL_PDF_PATH: '/app/pdf' # Optional, path for PDF files
  #     PDF_UPLOAD: ${DOCS_PDF_UPLOAD:-false} # Optional, upload enhanced PDFs to paperless-ngx
  #     PDF_REPLACE: 'false' # Optional and DANGEROUS, delete original after upload
  #     PDF_COPY_METADATA: 'true' # Optional, copy metadata from original document
  #     PDF_OCR_TAGGING: 'true' # Optional, add tag to processed documents
  #     PDF_OCR_COMPLETE_TAG: 'paperless-gpt-ocr-complete' # Optional, tag name

  #     # Docling Server
  #     # OCR_PROVIDER: 'docling'              # Use a Docling server
  #     # DOCLING_URL: 'http://your-docling-server:port' # URL of your Docling instance
  #     # DOCLING_IMAGE_EXPORT_MODE: "placeholder" # Optional, defaults to "embedded"
  #     # DOCLING_OCR_PIPELINE: "standard" # Optional, defaults to "vlm"
  #     # DOCLING_OCR_ENGINE: "easyocr" # Optional, defaults to "easyocr" (only used when `DOCLING_OCR_PIPELINE is set to 'standard')

  #     AUTO_OCR_TAG: 'paperless-gpt-ocr-auto' # Optional, default: paperless-gpt-ocr-auto
  #     OCR_LIMIT_PAGES: '0' # Optional, default: 5. Set to 0 for no limit.
  #     LOG_LEVEL: 'info' # Optional: debug, warn, error
  #     VISION_LLM_REQUESTS_PER_MINUTE: '5'
  #     LLM_REQUESTS_PER_MINUTE: '5'
  #   volumes:
  #     - ${DOCS_PROMPTS_VOL:-./prompts}:/app/prompts # Mount the prompts directory
  #     - ${DOCS_HOCR_VOL:-./hocr}:/app/hocr # Only if CREATE_LOCAL_HOCR is true
  #     - ${DOCS_PDF_VOL:-./pdf}:/app/pdf # Only if CREATE_LOCAL_PDF is true
  #   ports:
  #     - ${DOCS_GPT_PORT:-8080}:8080
  #   depends_on:
  #     - docs-paperless
  #   networks:
  #     - backend
  #     - frontend
