services:
  draw_excalidraw:
    image: excalidraw/excalidraw
    container_name: draw_excalidraw
    restart: unless-stopped
    ports:
      - ${DRAW_PORT}:80
    volumes:
      - draw_excalidraw:/data
    networks:
      - frontend
      - database
    labels:
      - io.cothrom.role="app"
      - io.cothrom.stack="draw"
      - io.cothrom.data="true"
      - io.cothrom.data.class="config"
      - io.cothrom.backup.policy="weekly"

volumes:
  draw_excalidraw:
