services:
  files_projectsend:
    image: lscr.io/linuxserver/projectsend:latest
    container_name: files_projectsend
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - files_config:/config
      - ${DATA_DIR}/files:/data
      - ${BACKUP_DIR}/files:/backup
    ports:
      - ${FILES_PORT}:80
    restart: unless-stopped
    networks:
      - frontend
      - database
    depends_on:
      - files_db

  files_db:
    container_name: files_db
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
        - MYSQL_DATABASE=files_projectsend
        - MYSQL_USER=projectsend
        - MYSQL_PASSWORD=${FILES_DB_PASSWORD}
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
    image: mariadb:noble
    restart: always
    volumes:
      - files_db:/var/lib/mysql
    networks:
      - database

volumes:
  files_config:
  files_db: