services:
  pdf_stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-fat
    container_name: pdf_stirling-pdf
    # ports:
    #   - '8080:8080'
    volumes:
      - pdf_stirling-pdf:/configs
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - io.cothrom.role="app"
      - io.cothrom.stack="pdf"
      - io.cothrom.data="true"
      - io.cothrom.data.class="config"
      - io.cothrom.backup.policy="weekly"

volumes:
  pdf_stirling-pdf:
