services:
  pdf_stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-fat
    container_name: pdf_stirling-pdf
    # ports:
    #   - '8080:8080'
    volumes:
      - pdf_stirling-pdf:/configs
    restart: unless-stopped
    networks:
      - frontend
    labels:
      ## database | app | proxy | worker | cache | storage
      - io.cothrom.role="app"
      - io.cothrom.stack="pdf"
      - io.cothrom.data="false"
      # database | files | config
      # - io.cothrom.data.class=database
      # postgres | mysql | mariadb | redis
      # - io.cothrom.db.engine=postgres
      # - io.cothrom.db.backup.command=pg_dump -U $POSTGRES_USER -d $POSTGRES_DB
      # - io.cothrom.db.backup.command=mysqldump -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE
      # daily | hourly | weekly
      # - io.cothrom.backup.policy=daily

volumes:
  pdf_stirling-pdf:
