###
### Definitions
###

x-op-app-network: &app-network
  networks:
    - database
    - frontend
    - backend
x-op-app-restart-policy: &app_restart_policy
  restart: unless-stopped

###
### Services
###

services:
  easyschematic:
    build:
      context: ./build
      dockerfile: dockerfile.easyschematic
    # ports:
      # - ${SCHEMATICS_PORT}:80
    <<: [*app_restart_policy, *app-network]
